### ISSUE TITLE
Add leetCode problems rating

### ISSUE THREAD

**Issue by chaman-rawat** [zubyj/leetcode-explained#42]
LeetCode difficulty rating does not reflect the actual difficulty of a problem.
[zerotrac/leetcode_problem_rating](https://github.com/zerotrac/leetcode_problem_rating) project can be useful to provide more detailed ratings.

<img width="413" alt="image" src="https://github.com/zubyj/leetcode-explained/assets/48222679/db06eb7c-aa91-422e-a02e-f4af98e7a23d">

Adding problems rating somewhere around to the difficulty might be a suitable placement.

**Comment by zubyj** [comment]
This is a great idea. We can the rank to each problem in the JSON file.

**Comment by zubyj** [comment]
It'll be added in v2.0.6. Cheers! 
 
5e4d933bcaf63ea7b79e57f0e01a0b998c3a548f
