### ISSUE TITLE
Panels hidden when logged into LC

### ISSUE THREAD

**Issue by ebarcly** [zubyj/leetcode-explained#50]
**System info:
Brave Browser -> [Version 1.58.135 Chromium: 117.0.5938.140 (Official Build) (x86_64)]
---**

While trying to use the extension I couldn't figure out why I wasn't being able to see anything on the panels(company tags or videos solutions on the solutions window). 

**Then noticed how the extension panel is hidden behind Leetcode's panels (see img):** 
<img width="887" alt="Screenshot 2023-10-08 at 7 21 08 PM" src="https://github.com/zubyj/leetcode-explained/assets/95110235/f0995159-ba6b-4227-b931-e02ea0e63aef">

**However when logged out of LC the extension works perfectly (see img):**
<img width="1918" alt="Screenshot 2023-10-08 at 7 28 46 PM" src="https://github.com/zubyj/leetcode-explained/assets/95110235/f1f26796-2479-4b20-83e8-ff2554f75a5f">
---
<img width="1286" alt="Screenshot 2023-10-08 at 7 29 02 PM" src="https://github.com/zubyj/leetcode-explained/assets/95110235/c562c892-ffdf-4696-a726-460a2ba80956">

**Comment by swapnilsachan03** [comment]
This is because when we're logged in, Leetcode uses the new dynamic layout feature, and when we're logged out, it uses the old static layout. The extension works fine in static layout, but Leetcode upgraded the layout a couple of weeks ago so now the extension is broken.

**Comment by zubyj** [comment]
I just updated the app to work with the new layout. Try it out!

**Comment by ebarcly** [comment]
> I just updated the app to work with the new layout. Try it out!

It works perfectly!
